def search(msg, word_list, max_length):
    for i in range(max_length, 0, -1):
        w = msg[:i]
        if w in word_list:
            return w


def solution(msg):
    answer = []

    # 길이가 1인 모든 단어를 포함하도록 사전을 초기화
    word_list = [0]
    for i in range(26):
        word_list.append(chr(i + 65))

    max_length = 1
    while msg:
        # 사전에서 현재 입력과 일치하는 가장 긴 문자열 w를 찾는다
        w = search(msg, word_list, max_length)
        
        # w에 해당하는 사전의 색인 번호를 출력하고 입력에서 w를 제거한다.
        answer.append(word_list.index(w))
        msg = msg[len(w):]

        # 입력에서 처리되지 않은 다음 글자가 남아있다면(c), w+c에 해당하는 단어를 사전에 등록한다
        if msg:
            c = msg[0]
            if not w + c in word_list:
                word_list.append(w+c)
                max_length = max(len(w+c), max_length)

    return answer

print(solution("THATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITISTHATTHATISISTHATTHATISNOTISNOTISTHATITITIS"))